version: '3.8'
services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U initdb']
      interval: 5s
      timeout: 5s
      retries: 5
  migrations:
    build:
      context: ./
      dockerfile: Dockerfile.migrations
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
  server:
    build: ./
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
volumes:
  postgres:
